# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python setup.py install 

# command to run tests, e.g. python setup.py test
# TODO: copy one .travis file from OCB branch to test it with a server on travis
script: python tests/runtests.py --test_xmlrpc
